server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    username: root
    password: Yi5582829.
    url: jdbc:mysql://127.0.0.1:3306/green?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: top.greenyi.green.bean

#showSql
logging:
  level:
    com:
      example:
        mapper : info
#Druid
druid:
  loginUsername: root
  loginPassword: root

#和风天气
weather:
  key: fddfaceae56c427281671b3cb3ef732a

#身份认证
idCard:
  appCode: 6e164e7200b0418594a31cd5b2f48741